Processing data in models
Osoro254Alex/Blog pull request #2
Opened 2023-03-29 17:49 UTC by Osoro254Alex

### I did the following in Processing data in models

- Make sure that there are no linter errors
- Make sure that you used correct flow Gitflow
- Make sure that you documented your work in a professional way
- Create model classes for all entities as shown in the ERD Diagram
- Set up associations between models.
- Remember that author_id column in posts table should be the foreign_key for the users table.
- Familiarize myself with rails c command
- Open rails console for your project.
- Create at least one user by running the code
- Your models should include some additional methods.

2023-03-29 19:01 UTC, cynthiainga requested changes
Hi @Osoro254Alex, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://user-images.githubusercontent.com/80612925/157397398-00904e26-60ec-46cd-9510-240661c250ef.gif)

## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Correct Gitflow ✔️ 

## Required Changes ♻️

- [ ] In the README file you have a broken link, the MIT link is broken. Please kindly fix that and add the MIT license to your README file 🙃 👍

## Optional suggestions

- [OPTIONAL] I notice that your commit messages are not in the imperative tense, the commit message should be written in the imperative tense. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8), kindly remember this for your next commit 😉 .

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 19:01 UTC, cynthiainga commented on app/models/post.rb
> +  end
- [OPTIONAL] Good job using one of the `Rails Active Callbacks` `after_save` to call the `#update_posts_counter` method every time a new post has been saved in the database, so then it would be better if you make the `update_posts_counter` method private 😁 😁

2023-03-29 19:01 UTC, cynthiainga commented on app/models/like.rb
> +  end
- [OPTIONAL] Good job using one of the Rails Active Callbacks `after_save` to call the `#update_likes_counter` method every time a new like has been saved in the database, so then it would be better if you make the `update_likes_counter` method private 😁 😁

2023-03-29 19:01 UTC, cynthiainga commented on app/models/comment.rb
> +  end
- [OPTIONAL] Good job using one of the Rails Active Callbacks `after_save` to call the `#update_comments_counter` method every time a new comment has been saved in the database, so then it would be better if you make the `update_comments_counter` method private 😁 😁

2023-03-30 05:26 UTC, BenMukebo approved these changes
### Hi @Osoro254Alex, 👋 

# STATUS: Approved  🎉 

Great work on making the changes requested by a previous reviewer :1st_place_medal:  
 Your project is complete!  There is nothing else to say other than... it's time to merge it
Congratulations! 🎉  🎉 🎉 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

### To Highlight :1st_place_medal: 
- Your Pull Request has a proper title and description. ✔️  
- The associations between models are set up correctly according to the given [ERD diagram](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/images/blog_app_erd.png). :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

- [OPTIONAL] As requested by the previous reviewer, Use descriptive commit messages.  The commit message should be written in the imperative tense and capitalized. [Read more about how to write descriptive commit messages](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8). Example:
  - :x: Wrong: added Descriptive README
  - :heavy_check_mark: Right: Add descriptive README 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @BenMukebo ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 05:26 UTC, BenMukebo commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [OPTIONAL] I also recommend that you delete the Note: 👇🏻 in your License section as these are instructions on how to complete the License section.

![image](https://user-images.githubusercontent.com/79058364/228737724-d520ee13-b88a-40b0-aac8-9127fb12226a.png)

2023-03-30 05:54 UTC, Osoro254Alex commented
@cynthiainga and @BenMukebo Thanks

2023-03-30 05:54 UTC, merged